eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    serviceUrl:
      defaultZone:  http://localhost:8761/eureka/
    enabled: true
#redis相关操作
spring:
  cache:
     redis:
       use-key-prefix: false
  thymeleaf:
    enabled: false
  mvc:
     view:
       prefix: /WEB-INF/views/
       suffix: .jsp
     static-path-pattern: /static/**
  resources:
     static-locations: classpath:/static,classpath:/templates,classpath:/resources
  security:
     basic:
        enabled: false
  management:
     security:
        enabled: false
  redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      jedis:
        pool:
          #最大连接数
          max-active: 8
          #最大等待时间
          max-wait: 5000
          #最大空闲链接
          max-idle: 100
          #最小空闲链接
          min-idle: 20
      timeout: 10000
  datasource:
      url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver